const axios = require('axios');

module.exports.config = {
  name: 'hugot',
  version: '1.0.0',
  hasPermission: 0,  // Default access (can be accessed by all users)
  description: 'Zerome command with 200 messages and Free Hugot API',
  usages: 'zerome [hugot/broken]',
  credits: 'Omega Team',
  cooldowns: 0,
  dependencies: {
    "axios": ""  // Dependency for external API requests (Free Hugot API)
  }
};

const messages = [
  "1. Welcome to Omega, your one-stop entertainment destination!",
  "2. Life is like a game — you can win or lose, but you never give up.",
  "3. Success comes to those who dare to try.",
  "4. Never stop dreaming, because dreams are the blueprint of your future.",
  "5. Don't wait for opportunities, create them.",
  "6. You are the architect of your own destiny.",
  "7. No matter how hard life gets, you have the strength to move forward.",
  "8. Every challenge is an opportunity in disguise.",
  "9. Take it one step at a time and success will follow.",
  "10. Don't let failures define you; let them refine you.",
  "11. Make your own luck by taking action.",
  "12. Hard work pays off, keep pushing!",
  "13. Keep the fire of ambition burning within.",
  "14. Every day is a new chance to change your life.",
  "15. Keep your head high and your dreams higher.",
  "16. A small step forward is still progress.",
  "17. Believe in yourself, no one else will if you don't.",
  "18. You are stronger than you think.",
  "19. Failures are just stepping stones to success.",
  "20. You’re not where you want to be yet, but you’re not where you used to be.",
  "21. Life doesn't wait, so neither should you.",
  "22. Do something today that your future self will thank you for.",
  "23. Let your actions speak louder than words.",
  "24. If you can dream it, you can achieve it.",
  "25. Don't just wish for success, work for it.",
  "26. You are capable of achieving greatness.",
  "27. The journey may be tough, but the destination is worth it.",
  "28. Keep pushing, even when it seems impossible.",
  "29. You are the sum of your choices, so make them wisely.",
  "30. Success is a result of hard work, patience, and perseverance.",
  "31. The best time to start is now.",
  "32. The only limit is the one you set for yourself.",
  "33. Today’s challenges are tomorrow’s triumphs.",
  "34. Your potential is endless.",
  "35. Dreams don't work unless you do.",
  "36. Focus on progress, not perfection.",
  "37. The future belongs to those who believe in the beauty of their dreams.",
  "38. Believe, work hard, achieve!",
  "39. Don’t wait for opportunities, create them.",
  "40. Set your goals high, and don’t stop until you get there.",
  "41. Every small victory is worth celebrating.",
  "42. Trust the process, the results will follow.",
  "43. Success is not final, failure is not fatal: it’s the courage to continue that counts.",
  "44. The harder you work, the luckier you get.",
  "45. You are closer to success than you think.",
  "46. Stay hungry, stay foolish.",
  "47. The only way to do great work is to love what you do.",
  "48. Perseverance is the key to unlocking success.",
  "49. Don’t count the days, make the days count.",
  "50. If you want to achieve greatness, stop asking for permission.",
  "51. When one door closes, another opens.",
  "52. Turn your wounds into wisdom.",
  "53. Don’t stop when you’re tired, stop when you’re done.",
  "54. Every setback is a setup for a comeback.",
  "55. Your future is created by what you do today, not tomorrow.",
  "56. Your only limit is you.",
  "57. Success is not measured by what you accomplish, but by the obstacles you overcome.",
  "58. Keep going, because you’re doing great!",
  "59. The sky’s the limit when you keep moving forward.",
  "60. Focus on what you can control, and let go of the rest.",
  "61. Don’t watch the clock; do what it does. Keep going.",
  "62. Be patient with yourself; nothing in nature blooms all year.",
  "63. Take chances, make mistakes, and learn from them.",
  "64. Make your dreams come true by taking consistent action.",
  "65. Don’t just exist, live your life to the fullest.",
  "66. Believe in your dreams, even when no one else does.",
  "67. Never let fear decide your future.",
  "68. Keep your face always toward the sunshine—and shadows will fall behind you.",
  "69. Life isn’t about waiting for the storm to pass; it’s about learning to dance in the rain.",
  "70. Your only limit is the one you place on yourself.",
  "71. Great things never come from comfort zones.",
  "72. When you feel like quitting, remember why you started.",
  "73. The only way to achieve the impossible is to believe it’s possible.",
  "74. You don’t have to be great to start, but you have to start to be great.",
  "75. The key to success is to focus on goals, not obstacles.",
  "76. Failure is just another step towards success.",
  "77. Do what you can, with what you have, where you are.",
  "78. Success doesn’t come to you, you go to it.",
  "79. If you believe in yourself, anything is possible.",
  "80. Keep moving forward and never look back.",
  "81. There’s no elevator to success, you have to take the stairs.",
  "82. Great things take time.",
  "83. Hard times don’t last, but tough people do.",
  "84. You are capable of amazing things.",
  "85. You are stronger than any excuse.",
  "86. Don’t stop until you’re proud.",
  "87. Your biggest regret will be the chance you didn’t take.",
  "88. Dream it. Believe it. Achieve it.",
  "89. Your potential is limitless.",
  "90. Nothing worth having comes easy.",
  "91. Strive for progress, not perfection.",
  "92. Keep your dreams alive.",
  "93. You are braver than you believe.",
  "94. You are the master of your destiny.",
  "95. Do something today that your future self will thank you for.",
  "96. Never stop improving.",
  "97. Success doesn’t happen overnight.",
  "98. Focus on the journey, not the destination.",
  "99. Your time is now. Make it count.",
  "100. If you can’t stop thinking about it, don’t stop working for it.",
  "101. Every challenge you face is an opportunity to grow.",
  "102. The harder the battle, the sweeter the victory.",
  "103. Don’t give up, your breakthrough is closer than you think.",
  "104. Dream big, work hard, stay focused.",
  "105. You are capable of more than you know.",
  "106. Today is the day to start something new.",
  "107. You don’t have to be perfect to be amazing.",
  "108. Hard work beats talent when talent doesn’t work hard.",
  "109. Nothing in life comes easy, but it’s all worth it.",
  "110. Success isn’t for the chosen few; it’s for those who are willing to work for it.",
  "111. Stay strong. Your time is coming.",
  "112. The only way to predict your future is to create it.",
  "113. Hard work and dedication lead to success.",
  "114. You’re closer to your goal than you think.",
  "115. Keep your eyes on the prize.",
  "116. Don’t stop now; keep going!",
  "117. Success doesn’t come to you, you go to it.",
  "118. The best way to predict your future is to create it.",
  "119. Great things never come from comfort zones.",
  "120. If it’s easy, it’s not worth it.",
  "121. Believe you can and you’re halfway there.",
  "122. Success is the sum of small efforts repeated day in and day out.",
  "123. Stay focused and never give up.",
  "124. The road to success is always under construction.",
  "125. Success is the result of preparation, hard work, and learning from failure.",
  "126. Take risks and do what you love.",
  "127. Your dreams are waiting for you to take action.",
  "128. Challenges are what make life interesting; overcoming them is what makes life meaningful.",
  "129. The bigger the challenge, the bigger the
