const axios = require('axios');

module.exports.config = {
  name: 'zerome',
  version: '1.0.0',
  hasPermission: 0,  // Default access for all users
  description: 'Zerome command with 200 Tagalog messages and Free Hugot API',
  usages: 'zerome [hugot]',
  credits: 'Omega Team',
  cooldowns: 0,
  dependencies: {
    "axios": ""  // Dependency for external API (Hugot API)
  }
};

const messages = [
  "1. Sa buhay, kailangan mong magpatawad para mag-move on.",
  "2. Ang puso ay parang cellphone, kung hindi mo inaalagaan, malulobat.",
  "3. Ang paghihirap ngayon ay may katumbas na saya sa hinaharap.",
  "4. Hindi lahat ng nawawala ay nawalan ng halaga.",
  "5. Kung masakit, ituloy mo lang. Ang sakit ay hindi pang-habambuhay.",
  "6. Sa bawat pagluha, may natutunang aral.",
  "7. Huwag mong gawing balakid ang mga pagkalugi sa buhay.",
  "8. Hindi mo kailangan magmadali, ang tamang oras ay darating din.",
  "9. Kung walang sagot, baka ang tanong ay mali.",
  "10. Ang mga sugat ng nakaraan ay maghihilom din balang araw.",
  "11. Walang matimtimang pagkakaibigan na hindi magkakaroon ng pag-aaway.",
  "12. Ang mga mahihirap na pagsubok ang nagbubukas ng pinto para sa tagumpay.",
  "13. Bawat pagkatalo ay hindi katapusan, ito ay isang pagkakataon para magsimula muli.",
  "14. Pag naiinis ka, ngumiti ka na lang, baka ‘yon ang pinaka-magandang solusyon.",
  "15. Ang pagiging tapat ay isang bagay na hindi kayang bilhin ng kahit anong yaman.",
  "16. Huwag mong gawing daan ang pagkatalo para mawalan ng pag-asa.",
  "17. Sa kabila ng lahat ng pagsubok, may araw ding sisikat.",
  "18. Ang hindi marunong lumingon sa pinagmulan ay hindi makararating sa paroroonan.",
  "19. Walang dahilan para hindi magsimula, dahil sa bawat simula, may bagong pagkakataon.",
  "20. Hindi lahat ng bagay ay naaayon sa plano, pero ang mahalaga, natututo tayo.",
  "21. Hindi lahat ng pinapakita ay tunay, minsan ang pinaka-magandang bagay ay nasa likod ng mga ulap.",
  "22. Ang paghihintay ay masakit, pero ang masakit na paghihintay ay may mga magagandang kasunod na bagay.",
  "23. Sa kabila ng dilim ng gabi, may bituin pa ring magbibigay liwanag.",
  "24. Ang bawat luha na nahulog ay may kasamang pangako ng isang mas maganda bukas.",
  "25. Wala sa lakas ng katawan, kundi sa lakas ng loob.",
  "26. Huwag mong gawing prublema ang bagay na wala kang kontrol.",
  "27. Minsan, ang pinakamagandang bagay sa buhay ay yaong mga hindi natin inaasahan.",
  "28. Hindi kailangan ng maraming salita, minsan sapat na ang pagkakaroon ng tiwala sa isa't isa.",
  "29. Kung ang buhay ay tula, ikaw ang pinakamatamis na berso.",
  "30. Ang bawat pagkatalo ay isang hakbang patungo sa tagumpay.",
  "31. Kahit ang pinakamadilim na ulap ay lilipas din.",
  "32. Ang mga sugat sa puso ay kayang maghilom, basta't matututo kang magpatawad.",
  "33. Minsan, kailangan mong maglakbay mag-isa upang madama mo kung gaano kalakas ang loob mo.",
  "34. Hindi lahat ng relasyon ay nagtatagal, pero lahat ng karanasan ay may aral.",
  "35. May mga bagay na hindi mo kayang kontrolin, pero may mga bagay na kayang-kaya mong baguhin.",
  "36. Hindi lahat ng nawawala ay hindi na babalik.",
  "37. Minsan, ang pinakamalaking pagkatalo ay isang bagong simula.",
  "38. Pagtanggap sa iyong mga pagkatalo ay hakbang patungo sa mas malalaking tagumpay.",
  "39. Kung gusto mo magbago, kailangan mong mag-umpisa ngayon.",
  "40. Sa bawat laban, may natutunang leksyon.",
  "41. Ang pagmamahal ay hindi tungkol sa kung gaano kahirap, kundi kung gaano katagal.",
  "42. Walang gustong magtaksil, kundi minsan lang talagang lumilihis ng landas.",
  "43. Ang mga pangarap ay may mga sagabal, ngunit hindi ibig sabihin ay hindi mo sila maabot.",
  "44. Ang pusong sugatan ay kayang maghilom kung pagbibigyan ng pagkakataon.",
  "45. Sa bawat bukas, may bagong pag-asa.",
  "46. Minsan, ang pinakamagandang bagay ay makikita mo kapag hindi mo hinahanap.",
  "47. Kung mapapagod ka na, magpahinga, pero wag kang susuko.",
  "48. Huwag mong gawing laban ang bawat problema, kundi isang pagkakataon na matuto.",
  "49. Kahit magkaibang landas, ang puso pa rin ay may tadhana.",
  "50. May mga bagay na hindi mo kayang ipaliwanag, ngunit nararamdaman mo.",
  "51. Hindi lahat ng masakit ay may dahilan, ngunit may mga aral na matutunan sa bawat sakit.",
  "52. Walang perpekto sa mundo, kaya't matuto tayong tanggapin ang ating mga kahinaan.",
  "53. Ang tamis ng tagumpay ay mas masarap kapag dumaan ka sa hirap.",
  "54. Huwag mong gawing hadlang ang takot sa iyong mga pangarap.",
  "55. Ang mga tunay na pagkakaibigan ay hindi nagtatapos dahil sa distansya.",
  "56. Ang mga sugat ng nakaraan ay maghihilom din kung magtutulungan.",
  "57. Walang tamang panahon, basta't may puso kang handang magsimula.",
  "58. Sa bawat pagkatalo, may mas matibay na patutunguhan.",
  "59. Tanggapin mo ang mga pagkatalo, kasi sila ang magdadala sayo sa tagumpay.",
  "60. Kung nasaktan ka, okay lang. Mag-move on at magpatuloy sa buhay.",
  "61. Ang lahat ng bagay ay may dahilan, kahit na hindi mo ito nakikita ngayon.",
  "62. Huwag mong gawing dahilan ang sakit upang sumuko.",
  "63. Kung maghihirap ka, maghihirap ka na may halaga.",
  "64. Minsan ang pinakamagandang bagay ay yung hindi mo inaasahan.",
  "65. Ang mga pagkatalo ay paghahanda sa mas magagandang bagay.",
  "66. Huwag mong gawing dahilan ang takot para hindi mag-take risks.",
  "67. Kung nadapa, magtuloy lang. May mga mas magagandang pagkakataon na naghihintay.",
  "68. Maglakbay ka na walang panghihinayang.",
  "69. Minsan kailangan mong i-let go ng mga bagay na hindi na magbabalik.",
  "70. Tanggapin ang mga pagkatalo, dahil sila ang magdadala sa'yo sa mga tagumpay.",
  "71. Magtiwala sa sarili at magpatuloy.",
  "72. Huwag matakot magtangkang mangarap.",
  "73. Ang sakit ay pansamantala, ngunit ang lakas na matutunan mula dito ay permanente.",
  "74. Ang lahat ng bagay ay may katapusan, at lahat ng katapusan ay may bagong simula.",
  "75. Ang mga bagay na hindi mo kayang baguhin ay nagpapalakas sa'yo.",
  "76. Walang tagumpay na makakamtan kung hindi magsasakripisyo.",
  "77. Magtiwala ka sa proseso, darating din ang tamang oras.",
  "78. Walang mananalo kung walang magiging laban.",
  "79. Kung ang puso ay sugatan, pahinga lang at maghilom.",
  "80. Ang buhay ay parang pag-ibig, minsan matamis, minsan mapait.",
  "81. Tanggapin ang lahat ng nangyayari, may magandang dahilan diyan.",
  "82. Minsan, ang pinakamagandang aral ay mula sa mga pagkatalo.",
  "83. Huwag matakot sa pag-ibig; matakot ka sa mga pagkakataon na hindi mo ito tinangkang subukan.",
  "84. May dahilan kung bakit hindi ka tin
